name: build and run

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  linux-aarch64-native:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        compiler: ["gcc", "clang"]

    steps:
    - uses: actions/checkout@v4
    - name: inspect hardware
      run: cat /proc/cpuinfo
    - name: install dependencies
      run: sudo apt-get install libmpfr-dev libmpc-dev clang qemu-user-static
    - name: configure
      run: cp config.mk.dist config.mk
    - name: make
      run: CC="${{ matrix.compiler }}" make -j
    - name: make check
      run: CC="${{ matrix.compiler }}" EMULATOR="qemu-aarch64-static" make check -j

  linux-x86-64-cross:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: ["gcc"]

    steps:
    - uses: actions/checkout@v4
    - name: inspect hardware
      run: cat /proc/cpuinfo
    - name: install dependencies
      run: sudo apt-get install libmpfr-dev libmpc-dev gcc-aarch64-linux-gnu qemu-user-static
    - name: configure
      run: cp config.mk.dist config.mk
    - name: make
      run: CC="${{ matrix.compiler }}" make -j
    - name: make check
      run: CC="${{ matrix.compiler }}" EMULATOR="qemu-aarch64-static" make check -j

  darwin-aarch64-native:
    runs-on: macos-15
    strategy:
      matrix:
        compiler: ["clang"]

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: brew install mpfr
    - name: configure
      run: cp config.mk.dist config.mk
    - name: update config
      run: sed -i -e 's/USE_GLIBC_ABI = 1/USE_GLIBC_ABI = 0/g' config.mk
    - name: make
      run: CC="${{ matrix.compiler }}" make -j
    - name: make check
      run: CC="${{ matrix.compiler }}" make check -j
