name: build and test master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        compiler: ["gcc", "clang"]

    steps:
    - uses: actions/checkout@v4
    - name: inspect hardware
      run: cat /proc/cpuinfo
    - name: install dependencies
      run: sudo apt-get install libmpfr-dev libmpc-dev clang qemu-user-binfmt
    - name: configure
      run: cp config.mk.dist config.mk
    - name: make
      run: CC="${{ matrix.compiler }}" make -j
    - name: make check
      run: CC="${{ matrix.compiler }}" make check -j
